name: Build and Push Gin app to Heroku

on:
  workflow_dispatch:
    
jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'

      - uses: actions/checkout@v2

      - name: build go app
        run: |
          cd gin
          go get -d -v
          go build -o bin/gin-app -v .

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets. HEROKU_APP_NAME }} 
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: ./gin