name: Build and Push Gin app to Heroku

on:
  workflow_dispatch:
    
jobs:
  build-deploy:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'

      - uses: actions/checkout@v2

      - name: build go app
        run: |
          cd gin
          go get -d -v
          go build -o bin/gin-app -v .

      - name: Add api remote origin
        run: |
          git remote add heroku-api https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      - name: Deploy api to Heroku
        run: |
          git subtree push --prefix gin heroku-api master  